{{- if .Values.lokiReader.enabled }}
# Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.lokiReader.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    {{- with .Values.lokiReader.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.lokiReader.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.lokiReader.service.type }}
  ports:
    - port: {{ .Values.lokiReader.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.lokiReader.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
# Pod Disruption Budget
{{- if .Values.lokiReader.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.lokiReader.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    {{- with .Values.lokiReader.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.lokiReader.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.lokiReader.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lokiReader.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring-stack.labels" . | nindent 4 }}
    {{- with .Values.lokiReader.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.lokiReader.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.lokiReader.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.lokiReader.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.lokiReader.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- include "monitoring-stack.labels" . | nindent 8 }}
        {{- with .Values.lokiReader.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.lokiReader.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.lokiReader.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.lokiReader.securityContext | nindent 8 }}
      containers:
        - name: {{ .Values.lokiReader.name }}
          image: "{{ .Values.lokiReader.image.repository }}:{{ .Values.lokiReader.image.tag }}"
          imagePullPolicy: {{ .Values.lokiReader.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.lokiReader.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.lokiReader.name }}-config
          volumeMounts:
            {{- range $name, $config := .Values.lokiReader.volumes }}
            - name: {{ $name }}
              mountPath: {{ $config.mountPath }}
            {{- end }}
          resources:
            {{- toYaml .Values.lokiReader.resources | nindent 12 }}
          {{- with .Values.lokiReader.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.lokiReader.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- range $name, $config := .Values.lokiReader.volumes }}
        - name: {{ $name }}
          {{- if $config.emptyDir }}
          emptyDir: {}
          {{- end }}
        {{- end }}
{{- end }} 