apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules
  namespace: monitoring
data:
  rules.yaml: |
    groups:
      - name: magic-xpi-rules
        interval: 1m
        rules:
          - record: magic_xpi_activity_logs
            expr: |
              {app="otel-collector"} 
              |~ `Body: Map\(` 
              | regexp `Body: Map\((?P<body>\{.*\})\)` 
              | line_format "{{.body}}" 
              | json
              | label_format flowid="{{.flowid}}"
              | label_format projectkey="{{.projectkey}}"
              | label_format severity="{{.severity}}"
              | label_format category="{{.category}}" 