apiVersion: v1
kind: Service
metadata:
  name: loki-reader-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: loki-reader
  ports:
    - protocol: TCP
      port: 80        # The port that the service will expose
      targetPort: 8080 # The port your container is listening on
  type: LoadBalancer   # Change to NodePort or LoadBalancer if needed
