apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  selector:
    app: prometheus-pushgateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
